---
title: "Homework 3"
author: "Justin Lau"
date: "11/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(ROCR)
library(tree)
library(maptree)
library(class)
library(lattice)
library(ggridges)
library(superheat)
library(ggplot2)
library(dendextend)
```

```{r}
drug_use <- read_csv('drug.csv',
col_names = c('ID','Age','Gender','Education','Country','Ethnicity',
'Nscore','Escore','Oscore','Ascore','Cscore','Impulsive',
'SS','Alcohol','Amphet','Amyl','Benzos','Caff','Cannabis','Choc','Coke','Crack','Ecstasy','Heroin','Ketamine',
'Legalh','LSD','Meth','Mushrooms','Nicotine','Semer','VSA'))

```

```{r}
drug_use <- drug_use %>% mutate_at(as.ordered, .vars=vars(Alcohol:VSA))
drug_use <- drug_use %>%
mutate(Gender = factor(Gender, labels=c("Male", "Female"))) %>%
mutate(Ethnicity = factor(Ethnicity, labels=c("Black", "Asian", "White",
"Mixed:White/Black", "Other",
"Mixed:White/Asian",
"Mixed:Black/Asian"))) %>%
mutate(Country = factor(Country, labels=c("Australia", "Canada", "New Zealand","Other", "Ireland", "UK", "USA")))
```

Question 1a
```{r}
drug_use <- drug_use %>%
  mutate(recent_cannabis_use=as.factor(ifelse(Cannabis>="CL3", "No", "Yes")))
```

1b
```{r}
drug_use_subset <- drug_use %>% select(Age:SS, recent_cannabis_use)
train = sample(1:nrow(drug_use_subset),1500)
drug_use_train = drug_use_subset[train,]
drug_use_test = drug_use_subset[-train,]
dim(drug_use_train)
dim(drug_use_test)
```

1c
```{r}
fit <- glm(recent_cannabis_use ~ .,data=drug_use_train, family=binomial)
summary(fit)
```

Question 2
```{r}
set.seed(1)
tree_parameters = tree.control(nobs=nrow(drug_use_train), minsize=10, mindev=1e-3)
drugtree <- tree(recent_cannabis_use~., drug_use_train, control=tree_parameters)
cv <- cv.tree(drugtree, FUN =prune.misclass, K=10 )
cv
best_size = min(cv$size[cv$dev ==315])
best_size
```

2b
```{r}
drugtree.pruned <- prune.misclass(drugtree, best = best_size)
draw.tree(drugtree.pruned, nodeinfo = TRUE, cex = 0.4)
```

2c
```{r}
drugtree_test <- tree(recent_cannabis_use~., drug_use_test, control=tree_parameters)
prob.training = predict(drugtree_test, drug_use_test, type="class")
table(true=drug_use_test$recent_cannabis_use, pred=prob.training)
```

```{r}
TPR <- 193/(193+20)
FPR <- 19/(19+153)
cat('TPR is', TPR, '\n')
cat('FPR is', FPR)

```

Question 3
```{r}
#Logisitic Regression
fit.test <- glm(recent_cannabis_use~., data=drug_use_test, family=binomial)
training = predict(fit.test, type="response")
pred = prediction(training, drug_use_test$recent_cannabis_use)
perf_log = performance(pred, measure="tpr", x.measure="fpr")
plot(perf_log, col='red')

pred_tree <- predict(drugtree.pruned,drug_use_test, type="vector")
tree.pred <- prediction(pred_tree[,2], drug_use_test$recent_cannabis_use)
perf_tree = performance(tree.pred, measure="tpr", x.measure="fpr")
plot(perf_tree, col='blue',  add=TRUE)
legend(.6,.4, legend=c("Logistic", "Tree"),
       col=c("red", "blue"), lty=1:2, cex=0.8)
```


3b
```{r}
auc_log = performance(pred, "auc")@y.values
auc_tree = performance(tree.pred, "auc")@y.values

cat("The AUC of logistic is", as.numeric(auc_log), '\n')
cat("The AUC of decision tree is", as.numeric(auc_tree))
```


Question 4
```{r}
leukemia_data <- read_csv("leukemia_data.csv")
```
```{r}
leukemia_data  <- leukemia_data %>%
  mutate(Type = factor(Type))

leukemia_data %>% count(Type, sort = TRUE)
```

BCR-ABL occurs the least in the data

4b
```{r}
leukemia <- leukemia_data %>% select(-Type)

pca <- prcomp(leukemia,scale=TRUE, center=TRUE)
sdev <- pca$sdev
pve <- sdev^2 / sum(sdev^2)
cumulative_pve <- cumsum(pve)
par(mfrow=c(1, 2))
plot(pve, type="l", xlab = "Principle Component",lwd=3)
plot(cumulative_pve, type="l", xlab = "Principle Component", lwd=3)
```

4c
```{r}
rainbow_colors <- rainbow(7)
plot_colors <- rainbow_colors[leukemia_data$Type]
plot(pca$x, col=plot_colors, cex=0)
text(pca$x, labels=leukemia_data$Type, cex=0.4, col=plot_colors)
```
T-ALL seems to be separated the most with regards to PC1
```{r}
head(sort(abs(pca$rotation[,1])))
```

4f
```{r}
leukemia_subset <- leukemia_data %>% filter(Type == "T-ALL" | Type == "TEL-AML1" | Type == "Hyperdip50")
dis = dist(leukemia_subset, method="euclidean")
leukemia.hc = hclust(dis, method="complete")
dend1 = as.dendrogram(leukemia.hc)
dend1 = color_branches(dend1, k=3)
dend1 = color_labels(dend1, k=3)
dend1 = set(dend1, "labels_cex", 0.3)
dend1 = set_labels(dend1, labels=leukemia_subset$Type[order.dendrogram(dend1)])
plot(dend1, horiz=T, main = "Dendrogram colored by three clusters")
```

```{r}
dend1 = as.dendrogram(leukemia.hc)
dend1 = color_branches(dend1, k=5)
dend1 = color_labels(dend1, k=5)
dend1 = set(dend1, "labels_cex", 0.3)
dend1 = set_labels(dend1, labels=leukemia_subset$Type[order.dendrogram(dend1)])
plot(dend1, horiz=T, main = "Dendrogram colored by 5 clusters")

```